.TH BIGTIME 1 20201009\-2.4.4 Linux "User Manuals"
.SH NAME
\fB\fCbigtime\fR \- customizable clock for the terminal
.SH SYNOPSIS
.B bigtime
[\fIOPTION\fR [\fIVALUE\fR]... \fIOPTION\fR [\fIVALUE\fR]]
.SH DESCRIPTION
.PP
Display the current time in big characters.
.PP
To render the time, \fBbigtime\fP reads a \fBdigits file\fR (see: \fBDIGITS FILE\fR).
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-small\-seconds\fR
Show seconds (normal size).
.TP
\fB\-S\fR, \fB\-\-big-seconds\fR
Show seconds (big size).
.TP
\fB\-d\fR, \fB\-\-date\fR
Show date.
.TP
\fB\-f\fR
Display time in 24h format.
.TP
\fB\-z\fR, \fB\-\-timezone\fR
Show timezone (i.e. +0200).
.TP
\fB\-F\fR, \fB\-\-foreground\fR \fI0..N\fR
Set foreground color (override \fB\-n\fR and \fB\-r\fR options).
.TP
\fB\-B\fR, \fB\-\-background\fR \fI0..N\fR
Set background color.
.TP
\fB\-r\fR, \fB\-\-rainbow\fR
Rainbow effect (override \fB\-n\fR and \fB\-F\fR options).
.TP
\fB\-N\fR, \fB\-\-no\-separator\fR
Do no display separators (horizontal layout only).
.TP
\fB\-n\fR, \fB\-\-random\fR
Random colors (override \fB\-r\fR and \fB\-F\fR options).
.TP
\fB\-C\fR, \fB\-\-list-colors\fR
Print available colors and exit.
.TP
\fB\-b\fR, \fB\-\-blink\fR
Enable blinking separators.
.TP
\fB\-a\fR, \fB\-\-alarm\fR \fI[H]H:MM[AM|am|PM|pm]\fR
Set daily alarm.
.br
For testing purpose, if keyword "\fBnow\fR" is used instead of a timestring, alarm rings immediately.
.TP
\fB\-o\fR, \fB\-\-snooze\fR \fI[M]M\fR
Set snooze duration in minutes (5-15).
.br
Default value is 9 minutes.
.TP
\fB\-t\fR, \fB\-\-timer\fR \fI[H]H:MM\fR
Set timer.
.TP
\fB\-i\fR, \fB\-\-signal\fR
Activate hourly time signal.
.TP
\fB\-v\fR, \fB\-\-vertical\fR
Display clock vertically.
.br
(Disable \fB\-b\fR option, since separators are not shown in this mode.)
.TP
\fB\-\-file\fR \fIFILENAME\fR
Use given \fIFILENAME\fR to render digits. Filepath and extension are not needed.
.br
\fBBigtime\fR looks for \fBdigits file\fR first in "/etc/bigtime" directory
.br
and then in "$HOME/.config/bigtime" directory.
.TP
\fB\-w\fR, \fB\-\-preview\fR
(With \fB\-\-file\fR) display a short preview of the selected file and exit.
.TP
\fB\-l\fR, \fB\-\-list\-files\fR
Print available \fBdigits files\fR and exit.
.TP
\fB\-e\fR, \fB\-\-edit\fR \fIFILENAME\fR
Create a new \fBdigits file\fR from a template, and open it.
.br
(Filepath and file extension are not needed.)
.br
If the given file already exists, open it for editing.
.TP
\fB\-q\fR, \fB-\-quiet\fR
Disable sound, alarm, timer and hourly time signal.
.TP
\fB\-h\fR, \fB-\-help\fR
Print this help and exit.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information and exit.
.SH KEY BINDINGS
.TP
a
Toggle daily alarm; set/confirm new alarm; stop alarm and disable \fBsnooze\fR mode.
.TP
f
Toggle 24h format / toggle AM/PM (alarm setting mode).
.TP
i
Toggle hourly time signal.
.TP
j
Select next digit (alarm/timer setting mode).
.TP
k
Select previous digit (alarm/timer setting mode).
.TP
q
Exit program.
.TP
R
refresh screen.
.TP
t
Toggle timer; set/confirm new timer.
.TP
space
Toggle display; stop; cancel (setting mode).
.SH TIMEZONE
.TP
To display the time for a different timezone, simply prepend \fBTZ\fR environment variable when invoking \fBbigtime\fR.

.TQ
For example:

.EX
.B
TZ=Europe/Paris bigtime
.EE
.SH DIGITS FILES
.PP
In a nutshell, a \fBdigits file\fR is a text file with the \fB.digits\fR extension that contains instructions on how to draw digits on the screen.
.br
Digits are sequences of 0s and 1s and are defined as semicolon separated lists.
.br
\fBBigtime\fR needs some clue about digits geometry (height and width in characters).
.br
Some other \fIoptional\fR parameters are available: \fBlayout\fR, \fBseconds\fR, \fBcolors\fR and \fBindicators\fR.
.br
> \fBlayout\fR and \fBseconds\fR parameters supersede corresponding command line options.
.br
> Color parameters are ignored if command line options regarding colors are set.
.br
> If these parameters are omitted or left blank, default values are used or values specified via the command line options.

.TP
\fB\- GEOMETRY \-\fR

.TP
\fBheight=\fIinteger\fR
height of a digit, in characters.
.TP
\fBwidth=\fIinteger\fR
width of a digit, in characters.
.TP
.B
These parameters are mandatory.
.TP
\fBsep_width=\fIinteger\fR
width of a separator, in characters.
.TP
Example:

.EX
.B
height=5
.br
.B
width=5
.B
sep_width=3
.EE
.TP
\fB\- LAYOUT \-\fR

.TP
\fBlayout=horizontal|vertical\fR

.TQ
The \fBlayout\fR optional parameter can be used to force the clock to display in a particular layout.

.TP
\fB\- COLORS \-\fR

.TP
\fBcolors=\fIlist\fR|rainbow|random\fR
.TP
\fBbackground=\fIinteger\fR
.TP
\fBforeground=\fIinteger\fR
.TP
\fBcolors\fR parameter can be either a semicolon separated list of 11 colors (so that every digit/separator is
.TQ
assigned a color), \fBrainbow\fR (equivalent of \fB\-\-rainbow\fR), or \fBrandom\fR (equivalent of \fB\-\-random\fR).
.TQ
Integer value is a color number as shown by \fB\-\-list-colors\fR option.
.TQ
\fINote:\fR colors command line options \fBsupersede\fR these parameters.

.TP
\fB\- SECONDS \- \fR

.TP
\fBseconds=big|small\fR

.TQ
Equivalent to \fB\-\-big-seconds\fR and \fB\-\-small-seconds\fR options.

.TP
\fB\- INDICATORS \-\fR

.TP
\fBam_indicator=\fIstring\fR
.TP
\fBpm_indicator=\fIstring\fR
.TP
\fBalarm_indicator=\fIchar\fR
.TP
\fBalarm_indicator=\fIchar\fR
.TP
\fBsnooze_indicator=\fIchar\fR
.TP
\fBtimer_indicator=\fIchar\fR

.TP
\fB\- DIGITS \-\fR

.TP
\fB0-9=\fIlist\fR\fR
.TP
\fBseparator=\fIlist\fR\fR
.TP
\fBblank=\fIlist\fR\fR
.TP
As stated before, a digit is defined by a semicolon separated list.
.TQ
For example:

.EX
.B
0=11111;11011;11011;11011;11111
.br
[...]
.br
.B
9=11111;11011;11111;00011;11111
.br
.B
separator=000;010;000;010;000
.br
.B
blank=000;000;000;000;000
.EE
.TP
\fB\- FILLED SPACE, EMPTY SPACE \-\fR

.TP
\fBchar=\fIchar\fR
character to display as filled space (1).
.TP
\fBspace=\fIchar\fR
character to display as empty space (0).
.TP
By default, when \fBbigtime\fR parses a file, 0s are replaced by whitespaces and 1s by "∎".
.TQ
But one can define characters as shown below:

.EX
.br
.B
char=@
.br
.B
space=-
.EE

.TP
Given the characters defined earlier, this (0):

.EX
.B
11111
.br
.B
11011
.br
.B
11011
.br
.B
11011
.br
.B
11111
.EE

.TQ
Becomes this:

.EX
.B
@@@@@
.br
.B
@@-@@
.br
.B
@@-@@
.br
.B
@@-@@
.br
.B
@@@@@
.EE

.TQ
So far, so good...  

.TP
\fB\- MAKE YOUR OWN DIGITS FILE \-\fR
.TP
You can find more examples in "/etc/bigtime/digits" directory
.TP
Custom \fBdigits files\fR must be stored in \fBbigtime\fR configuration directory:  

$HOME/.config/bigtime
.TP
You can use the \fB\-\-edit\fR option to create a new file from a template and edit it.
.TP
Note: Whenever \fBbigtime\fR encounters a mistake in a \fBdigits file\fR,
.TQ
it will throw an error and a useful description.

.SH AUTHOR
Written by Stéphane Meyer (Teegre).
.SH "REPORTING BUGS"
https://github.com/teegre/bigtime/issues
.SH LICENSE
License MIT.
.br
This is free software provided \fBAS IS\fR with \fBNO WARRANTY\fR. Feel free to change and redistribute.
